# MySQL database shared with tomcat containers.
db:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: admin
    MYSQL_DATABASE: giit
    MYSQL_USER: example_db_user
    MYSQL_PASSWORD: example_db_pass
  volumes:
    - ./sql:/docker-entrypoint-initdb.d
  ports:
    - "3306:3306"

# First node of the first Tomcat virtual host.
tomcat_1_node_1:
  image: tomcat:latest
  # Environment variables do not appear to be getting loaded the first time Tomcat starts!
  environment:
  #  VIRTUAL_HOST: tomcat_1.mulligan.ie
  #  VIRTUAL_PORT: 8080
    JDBC_URL: jdbc:mysql://db:3306/giit?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
    MYSQL_USER: example_db_user
    MYSQL_PASSWORD: example_db_pass
  volumes:
    - ./warfiel:/usr/local/tomcat/webapps
 # ports:
 #   - "8080:8080"
  links:
    - db

# Second node of the first Tomcat virtual host.
tomcat_1_node_2:
  image: tomcat:latest
  # Environment variables do not appear to be getting loaded the first time Tomcat starts!
  environment:
  #  VIRTUAL_HOST: tomcat_1.mulligan.ie
  #  VIRTUAL_PORT: 8080
    JDBC_URL: jdbc:mysql://db:3306/giit?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
    MYSQL_USER: example_db_user
    MYSQL_PASSWORD: example_db_pass
  volumes:
    - ./warfiel:/usr/local/tomcat/webapps
  #ports:
  #  - "8080:8080"
  links:
    - db

# nginx container that automatically creates a load balancer / reverse proxy across the 3 tomcat containers / 2 virtual hosts.
nginx:
#image: jwilder/nginx-proxy:latest
  image: nginx:1.13
  restart: always
  volumes:
    - ./nginx:/etc/nginx/conf.d
  ports:
    - "8081:80"
 #  - "443:443"
 # volumes:
 #   - /var/run/docker.sock:/tmp/docker.sock:ro

  links:
    - tomcat_1_node_1
    - tomcat_1_node_2
