apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
  creationTimestamp: null
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: db
    spec:
      containers:
      - image: mysql:latest
        name: db
        env:
        
        - name: MYSQL_DATABASE
          value: giit
        - name: MYSQL_PASSWORD
          value: example_db_pass
        - name: MYSQL_USER
          value: example_db_user
#        - name: MYSQL_ROOT_PASSWORD
#          valueFrom:
#              secretKeyRef:
#                name: mysql-pass
#                key: password
        ports:
        - containerPort: 3306
          name: db
status: {}
