apiVersion: extensions/v1beta1
kind: Deployment
metadata:
#  annotations:
#    kompose.cmd: kompose --file Doc/docker-compose.yml convert
#    kompose.version: 1.17.0 (a74acad)
#  creationTimestamp: null
  labels:
    name: db
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: giit
        - name: MYSQL_PASSWORD
          value: example_db_pass
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        - name: MYSQL_USER
          value: example_db_user
        - name: MYSQL_ROOT_PASSWORD
          value: password
        image: mysql:latest
        name: db
        ports:
        - name: db
          containerPort: 3306
status: {}
