apiVersion: v1
kind: Deployment
metadata:
#  annotations:
#    kompose.cmd: kompose --file Doc/docker-compose.yml convert
#    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    name: nginx
  name: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: nginx
    spec:
      containers:
      - image: nginx:1.13
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-pv-volume
      restartPolicy: Always
      volumes:
      - name: nginx-pv-volume
        persistentVolume:
          claimName: nginx-pv-volume
            volumeClaimTemplates:
      - metadata:
         name: task-pv-volume
        spec:
         accessModes: [ "ReadWriteOnce" ]
         storageClassName: "local-storage"
         resources:
           requests:
             storage: 100Mi
status: {}
