apiVersion: extensions/v1beta1
kind: Deployment
metadata:
#  annotations:
#    kompose.cmd: kompose --file Doc/docker-compose.yml convert
#    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    name: nginx
  name: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: nginx
    spec:
      containers:
      - image: yuvarajmindtree:nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-pv-volume
      restartPolicy: Always
status: {}
