apiVersion: v1
kind: Service
metadata:
  annotations:
#    kompose.cmd: kompose --file Doc/docker-compose.yml convert
#    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
#    io.kompose.service: nginx
  name: nginx
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 80
  selector:
#    io.kompose.service: nginx
    name: nginx
status:
  loadBalancer: {}
