apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file Doc/docker-compose.yml convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: tomcat
  name: tomcat
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: tomcat
    spec:
      containers:
      - env:
        - name: JDBC_URL
          value: jdbc:mysql://{$db}:3306/giit?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
        - name: MYSQL_PASSWORD
          value: example_db_pass
        - name: MYSQL_USER
          value: example_db_user
        image: tomcat:latest
        name: tomcat
        resources: {}
      restartPolicy: Always
status: {}
