apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: tomcat

#    kompose.cmd: kompose --file docker-compose.yml convert
#    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
#  labels:
#    io.kompose.service: tomcat-1-node-1
  name: tomcat
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 1
#  strategy:
#    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tomcat
#        io.kompose.service: tomcat-1-node-1
    spec:
     containers:
      - env:
        - name: JDBC_URL
          value: "jdbc:mysql://db:3306/giit?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true"
        - name: MYSQL_PASSWORD
          value: example_db_pass
        - name: MYSQL_USER
          value: example_db_user
        image: yuvarajmindtree/tomcat:latest
        name: tomcat
#        resources: {}
#      restartPolicy: Always
status: {}

