apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file /tmp/docker-compose.yml convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: tomcat-1-node-1
  name: tomcat-1-node-1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: tomcat-1-node-1
    spec:
      containers:
      - image: yuvarajmindtree/tomcat:latest
        name: tomcat-1-node-1
        resources: {}
      restartPolicy: Always
status: {}
